// loaders
export const LOGIN_ENABLE_LOADER = 'LOGIN_ENABLE_LOADER';
export const LOGIN_DISABLE_LOADER = 'LOGIN_DISABLE_LOADER';

// theming
export const TOGGLE_THEME = 'TOGGLE_THEME';

// login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_RESPONSE = 'LOGIN_RESPONSE';
export const LOGIN_LOADING_ENDED = 'LOGIN_LOADING_ENDED';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOG_OUT = 'LOG_OUT';

// explore
export const FETCH_BOOKLIST_REQUEST = 'FETCH_BOOKLIST_REQUEST';
export const FETCH_BOOKLIST_RESPONSE = 'FETCH_BOOKLIST_RESPONSE';
export const FETCH_LOADING = 'FETCH_LOADING';
export const FETCH_STOPLOADING = 'FETCH_STOPLOADING';

