// loaders
export const LOGIN_ENABLE_LOADER = 'LOGIN_ENABLE_LOADER';
export const LOGIN_DISABLE_LOADER = 'LOGIN_DISABLE_LOADER';

// theming
export const TOGGLE_THEME = 'TOGGLE_THEME';

// login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_RESPONSE = 'LOGIN_RESPONSE';
export const LOGIN_LOADING_ENDED = 'LOGIN_LOADING_ENDED';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOG_OUT = 'LOG_OUT';
export const SET_LOGGED_IN = 'SET_LOGGED_IN';
export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST';
export const USER_DETAILS_RESPONSE = 'USER_DETAILS_RESPONSE';
export const SET_TOKEN = 'SET_TOKEN';
export const SIGN_UP_REQUEST = 'SIGN_UP_REQUEST ';
export const SIGN_UP_RESPONSE = 'SIGN_UP_RESPONSE';
export const FORGET_PASSWORD_REQUEST = 'FORGET_PASSWORD_REQUEST';
export const FORGET_PASSWORD_RESPONSE = 'FORGET_PASSWORD_RESPONSE';
export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST';
export const UPDATE_PROFILE_RESPONSE = 'UPDATE_PROFILE_RESPONSE';
export const CLEAR_LOGIN_RESPONSE = 'CLEAR_LOGIN_RESPONSE';

// explore
export const GET_BOOK_REQUEST = 'GET_BOOK_REQUEST';
export const GET_BOOK_RESPONSE = 'GET_BOOK_RESPONSE';
export const FETCH_LOADING = 'FETCH_LOADING';
export const FETCH_STOPLOADING = 'FETCH_STOPLOADING';
export const SET_FAVORITE = 'SET_FAVORITE';
export const GET_FAVORITE_BOOKLIST_REQUEST = 'GET_FAVORITE_BOOKLIST_REQUEST';
export const GET_FAVORITE_BOOKLIST_RESPONSE = 'GET_FAVORITE_BOOKLIST_RESPONSE';
export const GET_BOOKDETAIL_REQUEST = 'GET_BOOKDETAIL_REQUEST ';
export const GET_BOOKDETAIL_RESPONSE = 'GET_BOOKDETAIL_RESPONSE';
export const ADD_TO_FAVORITE_REQUEST = 'ADD_TO_FAVORITE_REQUEST';
export const REMOVE_FROM_FAVORITE_REQUEST = 'REMOVE_FROM_FAVORITE_REQUEST';
